//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<bool> IndexPage { get; set; }
    }
}
